name: Example workflow for Firebase Distribution action
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@master
      - name: Upload artefact to Firebase Distribution  
        uses: ./
        with:
          appId: Test Name 
          token: Test Token
          groups: Test Group 
          file: Test File
